### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by waterboy550** [HussainDev/gridviewfullscreengallery#1]
I'm very new to Android Studio and would love to get this working so I can play around with it. I download the files then unzip them, then go to Import Project and select the build.grade and the project is created. I get some errors and it doesn't seem to run correctly after import, is there something I'm missing or something more I need to do? Any help or step by step would be great, I'm really looking forward to building off your project!

**Comment by HussainDev** [comment]
You are not importing the project correctly. 

To import a project to Android Studio:
Start Android Studio and close any open Android Studio projects.
From the Android Studio menu select File > New > Import Project. .
Select the Eclipse ADT project folder with the AndroidManifest.xml file and click Ok.
Select the destination folder and click Next.
